version: '3.3'

services:
  db:
    build:
      dockerfile: ./backend/docker/postgres/Dockerfile
    container_name: 'Apsql
    restart: on-failure
    ports:
      - 15432:5432
    environment:
      POSTGRES_USER: asci
      POSTGRES_PASSWORD: asci
      POSTGRES_DB: asci
      TZ: "America/New_York"
    volumes:
      - ./db:/var/lib/postgresql/data
  php:
    build:
      context: ./backend/
      dockerfile: ./docker/php/Dockerfile

    container_name: 'ASCI_php'
    ports:
      - 8081:80
    volumes:
      - ./backend/src/asci/:/opt/src/asci/
      - ./backend/www/:/var/www/html/
      - ./backend/log/:/opt/log/
    depends_on:
      - db

    environment:
      TZ: "America/New_York"

  react:
    build:
      context: ./frontend/
      dockerfile: ./docker/Dockerfile

    environment:
      - CHOKIDAR_USEPOLLING=true

    volumes:
      - ./frontend/build/:/app/build/

    container_name: 'ASCI_react'
    ports:
      - 3000:3000
