version: '3.3'

services:
  db:
    image: postgres
    container_name: 'ASCI_db'
    restart: on-failure
    ports:
      - 15432:5432
    environment:
      POSTGRES_PASSWORD: samplePassword
    volumes:
      - ./db:/var/lib/postgresql/data
  php:
    build:
      context: ./backend/
      dockerfile: ./docker/Dockerfile

    container_name: 'ASCI_php'
    ports:
      - 8081:80
    volumes:
      - ./backend/src/:/opt/src/
      - ./backend/www/:/var/www/html/
      - ./backend/log/:/opt/log/
    depends_on:
      - db
  react:
    build:
      context: ./frontend/
      dockerfile: ./docker/Dockerfile

    container_name: 'ASCI_react'
    ports:
      - 3000:3000
