export { default as Home } from "./Home";
export { default as CreateNewCourse } from "./CreateNewCourse";
export { default as CourseManagement } from "./CourseManagement";
export { default as UpdateChat } from "./UpdateChat";
export { default as EditCourse } from "./EditCourse";
export { default as SelectQuests } from "./SelectQuests";
export { default as QuestCard } from "./QuestCard";
export { default as ManagePoints } from "./ManagePoints";
export { default as PointsHome } from "./PointsHome";
